import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import '../testNode/Mention/styles.scss'
import '../testNode/Mention/MentionList.scss'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
